"""
Baker AI — Document Generator
Generates Word, Excel, PDF, and PowerPoint documents from Baker Scan output.
Called by /api/scan/generate-document endpoint in dashboard.py.
"""
import json
import os
import re
import tempfile
import uuid
from datetime import datetime

# Format-specific imports
from docx import Document
from docx.shared import Pt, Inches, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib import colors
from pptx import Presentation
from pptx.util import Inches as PptxInches, Pt as PptxPt

# Storage for generated files — maps file_id to filepath
GENERATED_FILES = {}


def generate_document(content, fmt, title, metadata=None):
    """
    Generate a document in the specified format.

    Args:
        content: str — markdown text (for docx/pdf) or JSON string (for xlsx/pptx)
        fmt: str — "docx", "xlsx", "pdf", or "pptx"
        title: str — document title
        metadata: dict — optional metadata (generated_by, timestamp)

    Returns:
        (file_id, filename, size_bytes)
    """
    generators = {
        "docx": _generate_docx,
        "xlsx": _generate_xlsx,
        "pdf": _generate_pdf,
        "pptx": _generate_pptx,
    }

    if fmt not in generators:
        raise ValueError(f"Unsupported format: {fmt}")

    file_id = str(uuid.uuid4())
    safe_title = re.sub(r'[^\w\s-]', '', title).strip().replace(' ', '_')
    date_str = datetime.utcnow().strftime('%Y-%m-%d')
    filename = f"{safe_title}_{date_str}.{fmt}"

    # Generate into temp directory
    tmp_dir = tempfile.gettempdir()
    filepath = os.path.join(tmp_dir, f"baker_{file_id}.{fmt}")

    generators[fmt](content, title, filepath, metadata)

    size_bytes = os.path.getsize(filepath)
    GENERATED_FILES[file_id] = {
        "filepath": filepath,
        "filename": filename,
        "format": fmt,
        "size_bytes": size_bytes,
        "created_at": datetime.utcnow().isoformat(),
    }

    return file_id, filename, size_bytes


def get_file(file_id):
    """Retrieve file info by ID. Returns None if not found or expired."""
    return GENERATED_FILES.get(file_id)


def cleanup_old_files(max_age_hours=24):
    """Remove files older than max_age_hours. Call periodically."""
    now = datetime.utcnow()
    expired = []
    for fid, info in GENERATED_FILES.items():
        created = datetime.fromisoformat(info["created_at"])
        if (now - created).total_seconds() > max_age_hours * 3600:
            expired.append(fid)
    for fid in expired:
        info = GENERATED_FILES.pop(fid)
        try:
            os.remove(info["filepath"])
        except OSError:
            pass


# ============================================================
# Generator: Word (.docx)
# ============================================================

def _generate_docx(content, title, filepath, metadata):
    """Parse markdown content -> Word document with clean business formatting."""
    doc = Document()

    # Title
    heading = doc.add_heading(title, level=0)
    heading.alignment = WD_ALIGN_PARAGRAPH.LEFT

    # Metadata line
    if metadata:
        meta_para = doc.add_paragraph()
        meta_run = meta_para.add_run(
            f"Generated by {metadata.get('generated_by', 'Baker Scan')} — "
            f"{metadata.get('timestamp', datetime.utcnow().isoformat())}"
        )
        meta_run.font.size = Pt(9)
        meta_run.font.color.rgb = RGBColor(128, 128, 128)
        doc.add_paragraph()  # spacer

    # Parse markdown lines into document elements
    lines = content.split('\n')
    for line in lines:
        stripped = line.strip()
        if not stripped:
            doc.add_paragraph()
            continue

        # Headings
        if stripped.startswith('### '):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith('## '):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith('# '):
            doc.add_heading(stripped[2:], level=1)
        # Bullet points
        elif stripped.startswith('- ') or stripped.startswith('* '):
            doc.add_paragraph(stripped[2:], style='List Bullet')
        # Numbered items
        elif re.match(r'^\d+\.\s', stripped):
            text = re.sub(r'^\d+\.\s', '', stripped)
            doc.add_paragraph(text, style='List Number')
        # Regular paragraph
        else:
            para = doc.add_paragraph()
            # Handle basic bold (**text**) and italic (*text*)
            parts = re.split(r'(\*\*.*?\*\*|\*.*?\*)', stripped)
            for part in parts:
                if part.startswith('**') and part.endswith('**'):
                    run = para.add_run(part[2:-2])
                    run.bold = True
                elif part.startswith('*') and part.endswith('*'):
                    run = para.add_run(part[1:-1])
                    run.italic = True
                else:
                    para.add_run(part)

    doc.save(filepath)


# ============================================================
# Generator: Excel (.xlsx)
# ============================================================

def _generate_xlsx(content, title, filepath, metadata):
    """
    Content should be JSON-parseable with structure:
    { "headers": ["Col A", "Col B"], "rows": [["val1", "val2"], ...] }
    Falls back to parsing markdown tables if JSON parsing fails.
    """
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = title[:31]  # Excel sheet name max 31 chars

    header_font = Font(bold=True, size=11, color="FFFFFF")
    header_fill = PatternFill(start_color="2C3E50", end_color="2C3E50", fill_type="solid")

    try:
        data = json.loads(content) if isinstance(content, str) else content
        headers = data.get("headers", [])
        rows = data.get("rows", [])
    except (json.JSONDecodeError, AttributeError):
        # Fallback: parse markdown table
        headers, rows = _parse_markdown_table(content)

    # Write headers
    for col_idx, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal='center')

    # Write data rows
    for row_idx, row_data in enumerate(rows, 2):
        for col_idx, value in enumerate(row_data, 1):
            cell = ws.cell(row=row_idx, column=col_idx, value=value)
            cell.alignment = Alignment(wrap_text=True)

    # Auto-width columns
    for col in ws.columns:
        max_length = 0
        col_letter = col[0].column_letter
        for cell in col:
            if cell.value:
                max_length = max(max_length, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = min(max_length + 4, 50)

    # Metadata row at bottom
    if metadata:
        skip_row = len(rows) + 3
        ws.cell(row=skip_row, column=1,
                value=f"Generated by {metadata.get('generated_by', 'Baker Scan')} — {metadata.get('timestamp', '')}")
        ws.cell(row=skip_row, column=1).font = Font(size=8, color="999999")

    wb.save(filepath)


def _parse_markdown_table(text):
    """Extract headers and rows from a markdown table string."""
    lines = [l.strip() for l in text.strip().split('\n') if l.strip()]
    headers = []
    rows = []
    for line in lines:
        if '|' not in line:
            continue
        cells = [c.strip() for c in line.split('|') if c.strip()]
        # Skip separator rows (---|---)
        if all(re.match(r'^[-:]+$', c) for c in cells):
            continue
        if not headers:
            headers = cells
        else:
            rows.append(cells)
    return headers, rows


# ============================================================
# Generator: PDF (.pdf)
# ============================================================

def _generate_pdf(content, title, filepath, metadata):
    """Markdown content -> clean PDF via reportlab."""
    doc = SimpleDocTemplate(
        filepath, pagesize=A4,
        leftMargin=inch, rightMargin=inch,
        topMargin=inch, bottomMargin=inch
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'BakerTitle', parent=styles['Title'],
        fontSize=18, spaceAfter=12,
        textColor=colors.HexColor('#1a1a2e')
    )
    heading_style = ParagraphStyle(
        'BakerH2', parent=styles['Heading2'],
        fontSize=14, spaceBefore=16, spaceAfter=8,
        textColor=colors.HexColor('#2C3E50')
    )
    body_style = ParagraphStyle(
        'BakerBody', parent=styles['Normal'],
        fontSize=10, leading=14, spaceAfter=6
    )
    meta_style = ParagraphStyle(
        'BakerMeta', parent=styles['Normal'],
        fontSize=8, textColor=colors.HexColor('#999999')
    )

    elements = []

    # Title
    elements.append(Paragraph(title, title_style))

    # Metadata
    if metadata:
        meta_text = (f"Generated by {metadata.get('generated_by', 'Baker Scan')} — "
                     f"{metadata.get('timestamp', '')}")
        elements.append(Paragraph(meta_text, meta_style))

    elements.append(Spacer(1, 12))

    # Parse markdown -> reportlab elements
    lines = content.split('\n')
    for line in lines:
        stripped = line.strip()
        if not stripped:
            elements.append(Spacer(1, 6))
            continue

        if stripped.startswith('## '):
            elements.append(Paragraph(stripped[3:], heading_style))
        elif stripped.startswith('# '):
            elements.append(Paragraph(stripped[2:], title_style))
        elif stripped.startswith('- ') or stripped.startswith('* '):
            bullet_text = f"\u2022 {stripped[2:]}"
            elements.append(Paragraph(bullet_text, body_style))
        else:
            # Convert **bold** to <b>bold</b> for reportlab
            text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', stripped)
            text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
            elements.append(Paragraph(text, body_style))

    doc.build(elements)


# ============================================================
# Generator: PowerPoint (.pptx)
# ============================================================

def _generate_pptx(content, title, filepath, metadata):
    """
    Content should be JSON-parseable with structure:
    { "slides": [{"title": "...", "bullets": ["...", ...]}, ...] }
    Falls back to splitting by ## headings if JSON parsing fails.
    """
    prs = Presentation()
    prs.slide_width = PptxInches(13.333)
    prs.slide_height = PptxInches(7.5)

    try:
        data = json.loads(content) if isinstance(content, str) else content
        slides = data.get("slides", [])
    except (json.JSONDecodeError, AttributeError):
        slides = _parse_markdown_slides(content)

    # Title slide
    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)
    slide.shapes.title.text = title
    if slide.placeholders[1]:
        meta_text = "Generated by Baker Scan"
        if metadata and metadata.get('timestamp'):
            meta_text += f" — {metadata['timestamp']}"
        slide.placeholders[1].text = meta_text

    # Content slides
    content_layout = prs.slide_layouts[1]  # Title + Content
    for slide_data in slides:
        slide = prs.slides.add_slide(content_layout)
        slide.shapes.title.text = slide_data.get("title", "")

        body = slide.placeholders[1]
        tf = body.text_frame
        tf.clear()

        bullets = slide_data.get("bullets", [])
        for i, bullet in enumerate(bullets):
            if i == 0:
                tf.paragraphs[0].text = bullet
            else:
                p = tf.add_paragraph()
                p.text = bullet
            tf.paragraphs[-1].font.size = PptxPt(18)

    prs.save(filepath)


def _parse_markdown_slides(text):
    """Split markdown by ## headings into slide structures."""
    slides = []
    current_slide = None

    for line in text.split('\n'):
        stripped = line.strip()
        if stripped.startswith('## '):
            if current_slide:
                slides.append(current_slide)
            current_slide = {"title": stripped[3:], "bullets": []}
        elif current_slide and (stripped.startswith('- ') or stripped.startswith('* ')):
            current_slide["bullets"].append(stripped[2:])
        elif current_slide and stripped and not stripped.startswith('#'):
            current_slide["bullets"].append(stripped)

    if current_slide:
        slides.append(current_slide)

    return slides


# ============================================================
# Professional Dossier DOCX Generator (ART-1)
# ============================================================

# Colors
_NAVY = RGBColor(0x1a, 0x1a, 0x2e)
_DARK_BLUE = RGBColor(0x2C, 0x3E, 0x50)
_BLUE_ACCENT = RGBColor(0x0a, 0x6f, 0xdb)
_GRAY = RGBColor(0x80, 0x80, 0x80)
_LIGHT_GRAY = RGBColor(0xCC, 0xCC, 0xCC)
_WHITE = RGBColor(0xFF, 0xFF, 0xFF)


def _add_thin_border(paragraph, color="1a1a2e"):
    """Add a thin bottom border to a paragraph (used as horizontal rule)."""
    pPr = paragraph._p.get_or_add_pPr()
    pBdr = OxmlElement('w:pBdr')
    bottom = OxmlElement('w:bottom')
    bottom.set(qn('w:val'), 'single')
    bottom.set(qn('w:sz'), '4')
    bottom.set(qn('w:space'), '4')
    bottom.set(qn('w:color'), color)
    pBdr.append(bottom)
    pPr.append(pBdr)


def _set_cell_shading(cell, color_hex):
    """Set background shading on a table cell."""
    shading = OxmlElement('w:shd')
    shading.set(qn('w:fill'), color_hex)
    shading.set(qn('w:val'), 'clear')
    cell._tc.get_or_add_tcPr().append(shading)


def _add_header_footer(doc, title_text="Baker Research Dossier"):
    """Add header and footer to the document."""
    for section in doc.sections:
        # Header
        header = section.header
        header.is_linked_to_previous = False
        hp = header.paragraphs[0] if header.paragraphs else header.add_paragraph()
        hp.text = ""
        run = hp.add_run(title_text)
        run.font.size = Pt(8)
        run.font.color.rgb = _GRAY
        hp.alignment = WD_ALIGN_PARAGRAPH.LEFT
        _add_thin_border(hp, "CCCCCC")

        # Footer with page number
        footer = section.footer
        footer.is_linked_to_previous = False
        fp = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        fp.text = ""
        fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = fp.add_run("Page ")
        run.font.size = Pt(8)
        run.font.color.rgb = _GRAY
        # Page number field
        fld_char1 = OxmlElement('w:fldChar')
        fld_char1.set(qn('w:fldCharType'), 'begin')
        run._r.append(fld_char1)
        instr = OxmlElement('w:instrText')
        instr.set(qn('xml:space'), 'preserve')
        instr.text = ' PAGE '
        run._r.append(instr)
        fld_char2 = OxmlElement('w:fldChar')
        fld_char2.set(qn('w:fldCharType'), 'end')
        run._r.append(fld_char2)


def _add_cover_page(doc, subject_name, subject_type, specialists_text, date_str):
    """Add a professional cover page."""
    # Top spacer
    for _ in range(6):
        doc.add_paragraph()

    # Title
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_para.add_run("RESEARCH DOSSIER")
    run.font.size = Pt(28)
    run.font.color.rgb = _NAVY
    run.bold = True
    run.font.name = "Calibri"

    doc.add_paragraph()

    # Subject name
    subj_para = doc.add_paragraph()
    subj_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subj_para.add_run(subject_name)
    run.font.size = Pt(22)
    run.font.color.rgb = _DARK_BLUE
    run.font.name = "Calibri"

    # Subject type
    type_para = doc.add_paragraph()
    type_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = type_para.add_run(subject_type.upper())
    run.font.size = Pt(11)
    run.font.color.rgb = _GRAY
    run.font.name = "Calibri"

    # Spacer
    for _ in range(4):
        doc.add_paragraph()

    # Thin rule
    rule = doc.add_paragraph()
    rule.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _add_thin_border(rule, "CCCCCC")

    # Metadata block
    meta_table = doc.add_table(rows=4, cols=2)
    meta_table.autofit = True
    meta_table.columns[0].width = Inches(2)
    meta_table.columns[1].width = Inches(4)

    labels = ["Date", "Classification", "Specialists", "Prepared by"]
    values = [date_str, "CONFIDENTIAL", specialists_text,
              "Baker Research Engine"]

    for i, (label, value) in enumerate(zip(labels, values)):
        left = meta_table.cell(i, 0)
        right = meta_table.cell(i, 1)
        lp = left.paragraphs[0]
        rp = right.paragraphs[0]
        lr = lp.add_run(label)
        lr.font.size = Pt(10)
        lr.font.color.rgb = _GRAY
        lr.font.name = "Calibri"
        rr = rp.add_run(value)
        rr.font.size = Pt(10)
        rr.font.color.rgb = _NAVY
        rr.font.name = "Calibri"
        if label == "Classification":
            rr.bold = True

    # Remove table borders
    for row in meta_table.rows:
        for cell in row.cells:
            tc = cell._tc
            tcPr = tc.get_or_add_tcPr()
            tcBorders = OxmlElement('w:tcBorders')
            for edge in ('top', 'left', 'bottom', 'right'):
                element = OxmlElement(f'w:{edge}')
                element.set(qn('w:val'), 'none')
                element.set(qn('w:sz'), '0')
                element.set(qn('w:space'), '0')
                element.set(qn('w:color'), 'auto')
                tcBorders.append(element)
            tcPr.append(tcBorders)

    # Page break after cover
    doc.add_page_break()


def _render_markdown_section(doc, content):
    """Render markdown content into Word document elements with professional formatting."""
    lines = content.split('\n')
    for line in lines:
        stripped = line.strip()

        if not stripped:
            # Skip blank lines — paragraph spacing handles visual gaps
            continue

        # Horizontal rule → thin border paragraph
        if stripped in ('---', '***', '___'):
            rule = doc.add_paragraph()
            _add_thin_border(rule, "CCCCCC")
            continue

        # Headings
        if stripped.startswith('#### '):
            h = doc.add_heading(stripped[5:], level=4)
            for run in h.runs:
                run.font.name = "Calibri"
                run.font.size = Pt(11)
                run.font.color.rgb = _DARK_BLUE
            continue
        if stripped.startswith('### '):
            h = doc.add_heading(stripped[4:], level=3)
            for run in h.runs:
                run.font.name = "Calibri"
                run.font.size = Pt(12)
                run.font.color.rgb = _DARK_BLUE
            continue
        if stripped.startswith('## '):
            # This is a specialist section header — handled by caller
            h = doc.add_heading(stripped[3:], level=2)
            for run in h.runs:
                run.font.name = "Calibri"
                run.font.size = Pt(14)
                run.font.color.rgb = _NAVY
                run.bold = True
            continue
        if stripped.startswith('# '):
            h = doc.add_heading(stripped[2:], level=1)
            for run in h.runs:
                run.font.name = "Calibri"
                run.font.size = Pt(16)
                run.font.color.rgb = _NAVY
            continue

        # Bullet points
        if stripped.startswith('- ') or stripped.startswith('* '):
            p = doc.add_paragraph(style='List Bullet')
            _add_inline_formatting(p, stripped[2:])
            for run in p.runs:
                run.font.name = "Calibri"
                run.font.size = Pt(11)
            continue

        # Sub-bullets
        if stripped.startswith('  - ') or stripped.startswith('  * '):
            p = doc.add_paragraph(style='List Bullet 2')
            _add_inline_formatting(p, stripped[4:])
            for run in p.runs:
                run.font.name = "Calibri"
                run.font.size = Pt(10)
            continue

        # Numbered items
        if re.match(r'^\d+\.\s', stripped):
            text = re.sub(r'^\d+\.\s', '', stripped)
            p = doc.add_paragraph(style='List Number')
            _add_inline_formatting(p, text)
            for run in p.runs:
                run.font.name = "Calibri"
                run.font.size = Pt(11)
            continue

        # Regular paragraph
        para = doc.add_paragraph()
        _add_inline_formatting(para, stripped)
        for run in para.runs:
            run.font.name = "Calibri"
            run.font.size = Pt(11)


def _add_inline_formatting(paragraph, text):
    """Parse **bold** and *italic* inline markdown and add runs to paragraph."""
    parts = re.split(r'(\*\*.*?\*\*|\*.*?\*)', text)
    for part in parts:
        if part.startswith('**') and part.endswith('**'):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        elif part.startswith('*') and part.endswith('*'):
            run = paragraph.add_run(part[1:-1])
            run.italic = True
        else:
            paragraph.add_run(part)


def generate_dossier_docx(dossier_md, subject_name, subject_type,
                          specialists_text, filepath):
    """
    Generate a professional McKinsey-style research dossier .docx.

    This splits the markdown by ## sections (specialist headers) and adds:
    - Cover page with metadata
    - Page breaks between specialist sections
    - Professional fonts (Calibri) and consistent styling
    - Header/footer with page numbers
    - Horizontal rules as thin borders

    Args:
        dossier_md: Full dossier markdown content
        subject_name: Name of the research subject
        subject_type: Type (person, company, etc.)
        specialists_text: Comma-separated specialist names
        filepath: Output .docx file path
    """
    doc = Document()

    # Set default font + paragraph spacing for readability
    style = doc.styles['Normal']
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)
    font.color.rgb = RGBColor(0x33, 0x33, 0x33)
    # Line spacing 1.15 + 6pt after paragraph — much more readable
    style.paragraph_format.line_spacing = 1.15
    style.paragraph_format.space_after = Pt(6)
    style.paragraph_format.space_before = Pt(0)

    # Heading styles — add spacing above for visual separation
    for lvl in (1, 2, 3, 4):
        try:
            hstyle = doc.styles[f'Heading {lvl}']
            hstyle.paragraph_format.space_before = Pt(18 if lvl <= 2 else 12)
            hstyle.paragraph_format.space_after = Pt(6)
        except Exception:
            pass

    # List styles — tighter spacing
    for lst in ('List Bullet', 'List Bullet 2', 'List Number'):
        try:
            lstyle = doc.styles[lst]
            lstyle.paragraph_format.space_after = Pt(3)
            lstyle.paragraph_format.space_before = Pt(1)
            lstyle.paragraph_format.line_spacing = 1.15
        except Exception:
            pass

    # Set narrow margins
    for section in doc.sections:
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.0)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)

    date_str = datetime.utcnow().strftime("%d %B %Y")

    # 1. Cover page
    _add_cover_page(doc, subject_name, subject_type, specialists_text, date_str)

    # 2. Header/footer (applied to all sections)
    _add_header_footer(doc)

    # 3. Split content by ## sections and render with page breaks
    # Skip the cover-page markdown (# title, metadata lines, first ---)
    sections = re.split(r'\n(?=## )', dossier_md)
    is_first_section = True

    for section_md in sections:
        section_md = section_md.strip()
        if not section_md:
            continue

        # Skip the top-level header block (# Research Dossier: ...)
        if section_md.startswith('# ') and not section_md.startswith('## '):
            # This is the metadata header — skip (cover page handles it)
            continue

        # Page break between specialist sections (not before the first)
        if section_md.startswith('## ') and not is_first_section:
            doc.add_page_break()

        if section_md.startswith('## '):
            is_first_section = False

        # Skip the footer line
        if section_md.startswith('*Generated by Baker'):
            continue

        _render_markdown_section(doc, section_md)

    # Final footer note
    doc.add_paragraph()
    rule = doc.add_paragraph()
    _add_thin_border(rule, "CCCCCC")
    footer_para = doc.add_paragraph()
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_para.add_run(
        f"Generated by Baker Research Engine  |  {date_str}  |  CONFIDENTIAL"
    )
    run.font.size = Pt(8)
    run.font.color.rgb = _GRAY
    run.font.name = "Calibri"

    doc.save(filepath)
